# Generated by Django 2.2.4 on 2019-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20190907_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
